drop table person if exists;

create table person (emplid bigint generated by default as identity (start with 1), firstName varchar(255), 
lastName varchar(255),  gender varchar(255), primary key (emplid))
