drop table personTbl if exists;


create table personTbl (personId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, increment by 1) PRIMARY KEY, personFirstName varchar(50) not null, personLastName varchar(50) not null );
